#!/bin/bash

set -x
export

#------------------------------------------------------------------------------
# Install SSL certificates:
#------------------------------------------------------------------------------

[ "${SSL_TRUST}" ] && {

  IFS=',' read -ra ADDR <<< "${SSL_TRUST}"

  # For each URL:
  for i in "${ADDR[@]}"; do

    # Set variables:
    ALIAS=$(echo ${i} | tr .: _)

    # Get the remote certificate:
    echo "[init] Downloading ${ALIAS} certificate..."
    echo | openssl s_client -showcerts -connect ${i} 2>/dev/null | \
    sed -n '/-BEGIN/,/-END/ p' > /tmp/${ALIAS}.pem

    # Verify we have something usable:
    grep -q CERTIFICATE /tmp/${ALIAS}.pem && {

      # Import the certificate (java):
      echo "[init] Importing ${ALIAS} certificate (java)..."
      keytool -import -trustcacerts -noprompt -file /tmp/${ALIAS}.pem \
      -alias ${ALIAS} -keystore /etc/pki/java/cacerts \
      -storepass changeit

      # Import the certificate (system):
      echo "[init] Importing ${ALIAS} certificate (system)..."
      mv /tmp/${ALIAS}.pem /etc/pki/ca-trust/source/anchors/
      update-ca-trust

    } || echo "[init] Ops! Cannot retrieve the ${ALIAS} certificate"

  done
}

#------------------------------------------------------------------------------
# Run:
#------------------------------------------------------------------------------

ls $MESOS_SANDBOX

echo "I am: $0"
x=($@)
echo "Now running: ${x[@]:1}"
exec ${x[@]:1}
